export enum MessageActionType {
  SEND_MESSAGE_COMMAND = 'pubnub/SEND_MESSAGE_COMMAND',
  MESSAGE_RECEIVED = 'pubnub/MESSAGE_RECEIVED',
  SENDING_MESSAGE = 'pubnub/SENDING_MESSAGE',
  MESSAGE_SENT = 'pubnub/MESSAGE_SENT',
  ERROR_SENDING_MESSAGE = 'pubnub/ERROR_SENDING_MESSAGE',
}
